let lwarr=[
    {
        "A":"ACM-TAP",
        "B":"./img/lw1.png",
        "C":"Creating word paintings jointly considering semantics, attention and aesthetics",
        "D":"unsong Zhang, Zuyi Yang, Linchengyu Jin, and Zhitang Lu",
        "E":"ACM Transactions on Applied Perception",
        "F":"In this paper, we present a content-aware method for generating a word painting. Word painting is a composite artwork made from the assemblage of words extracted from a given text, which carries similar semantics and visual features to a given source image. However, word painting, usually created by skilled artists, involves tedious manual processes, especially when generating streamlines and laying out text. Hence, we provide an easy method to create word paintings for users. How to design textural layout that simultaneously conveys the input image and enables easy access to the semantic theme, is the key challenge to generate a visually pleasing word painting. To address this issue, given an image and its content related text, we first decompose the input image into several regions and approximate each region with a smooth vector field. Simultaneously, through analyzing the input text, we extract weighted keywords as the graphic elements. Then, to measure the likelihood of positions in the input image that attracts observers’ attention, we generate a saliency map with our trained visual attention model. Finally, jointly considering visual attention and aesthetic rules, we propose an energy-based optimization framework to arrange extracted keywords into the decomposed regions and synthesize a word painting. Experimental results and user studies show that this method is able to generate a fashionable and appealing word painting."
    },
    {
        "A":"NATURE",
        "B":"./img/lw2.png",
        "C":"Precise segmentation of densely interweaving neuron clusters using G-Cut",
        "D":"Rui Li, Muye Zhu, Junning Li, Michael S. Bienkowski,  Junsong Zhang,  and Hong-Wei Dong",
        "E":"Nature Communications",
        "F":"Characterizing the precise three-dimensional morphology and anatomical context of neurons is crucial for neuronal cell type classification and circuitry mapping. Recent advances in tissue clearing techniques and microscopy make it possible to obtain image stacks of intact, interweaving neuron clusters in brain tissues. As most current 3D neuronal morphology reconstruction methods are only applicable to single neurons, it remains challenging to reconstruct these clusters digitally. To advance the state of the art beyond these challenges, we propose a fast and robust method named G-Cut that is able to automatically segment individual neurons from an interweaving neuron cluster. Across various densely inter- connected neuron clusters, G-Cut achieves significantly higher accuracies than other state-of-the-art algorithms. G-Cut is intended as a robust component in a high throughput informatics pipeline for large-scale brain mapping projects."
    },
    {
        "A":"《中国科学》",
        "B":"./img/lw3.png",
        "C":"考虑笔画和拓扑结构的字形美化方法",
        "D":"戴庆辉, 张俊松",
        "E":"《中国科学》出版社",
        "F":"本文提出了一种基于在线手写输入的字形美化方法.首先给定手写体的笔画和拓扑结构的形式化描述;然后借助拓扑结构和笔画的稳定性计算,采用类似轮盘赌的方法从用户手写样本中得到最佳的拓扑结构和笔画集,并分别对输入汉字的空间布局和各个笔画进行美化;最后通过分析书法理论中 “笔断意连”的几种常见模式,确定需要笔断意连的笔画,实现笔画之间的呼应关系优化,从而得到符合书法审美要求的字形"
    },
    {
        "A":"IEEE-TVCG",
        "B":"./img/lw4.png",
        "C":"Generating Multi-Destination Maps",
        "D":"Junsong Zhang, Jiepeng Fan, and Zhenshan Luo",
        "E":"IEEE Transactions on Visualization and Computer Graphics",
        "F":"Multi-destination maps are a kind of navigation maps aimed to guide visitors to multiple destinations within a region, which can be of great help to urban visitors. However, they have not been developed in the current online map service. To address this issue, we introduce a novel layout model designed especially for generating multi-destination maps, which considers the global and local layout of a multi-destination map. We model the layout problem as a graph drawing that satisfies a set of hard and soft constraints. In the global layout phase, we balance the scale factor between ROIs. In the local layout phase, we make all edges have good visibility and optimize the map layout to preserve the relative length and angle of roads. We also propose a perturbation-based optimization method to find an optimal layout in the complex solution space. The multi-destination maps generated by our system are potential feasible on the modern mobile devices and our result can show an overview and a detail view of the whole map at the same time. In addition, we perform a user study to evaluate the effectiveness of our method, and the results prove that the multi-destination maps achieve our goals well."
    },
    {
        "A":"ACM-TAP",
        "B":"./img/lw5.png",
        "C":"Computational Aesthetic Evaluation of Logos",
        "D":"Jiajing Zhang, Jinhui Yu, Kang Zhang, Xianjun Sam Zhang,  and Junsong Zhang",
        "E":"ACM Transactions on Applied Perception",
        "F":"Computational aesthetics has become an active research field in recent years, but there have been few attempts in computational aesthetic evaluation of logos. In this article, we restrict our study on black-and-white logos, which are professionally designed for name-brand companies with similar properties, and apply perceptual models of standard design principles in computational aesthetic evaluation of logos. We define a group of metrics to evaluate some aspects in design principles such as balance, contrast, and harmony of logos. We also collect human ratings of balance, contrast, harmony , and aesthetics of 60 logos from 60 volunteers. Statistical linear regression models are trained on this database using a supervised machine-learning method. Experimental results show that our model-evaluated balance, contrast, and harmony have highly significant correlation of over 0.87 with human evaluations on the same dimensions. Finally , we regress human-evaluated aesthetics scores on model-evaluated balance, contrast, and harmony . The resulted regression model of aesthetics can predict human judgments on perceived aesthetics with a high correlation of 0.85. Our work provides a machine-learning-based reference framework for quantitative aesthetic evaluation of graphic design patterns and also the research of exploring the relationship between aesthetic perceptions of human and computational evaluation of design principles extracted from graphic designs.  "
    }
    
]

let newsarr=[
    {
        "title":"线性规划模型与运筹学原理",
        "ds":"导师：Ming Gu   加州大学数学系终身教授",
        "jj":"项目内容：涉及计算covid-19数量增长模型、和太阳系行星运行轨道的模拟计算。",
        "img":"./img/img1.jpg",
        "time":"2022-03-06",
        "body":"<p> 提供的一项为期五年、价值 1.49 亿美元的拨款合作伙伴关系的五家机构之一，旨在解决阿尔茨海默病的健康差异问题研究。这笔赠款将继续 健康和老龄化大脑研究——健康差异 (HABS-HD)，这是迄今为止在不同社区进行的最全面的阿尔茨海默病 (AD) 研究。该项目的主要研究人员 包括北德克萨斯大学健康科学中心的 Sid O-Bryant 博士和 Leigh Johnson 博士；加州大学旧金山分校威尔神经科学研究所的医学博士 Kristine Yaffe；Robert Rissman，加州大学圣地亚哥分校博士；和南加州大学的 Arthur W. Toga 博士。 AD 研究中最重大的挑战之一是确定生物标志物，以确定谁有患这种疾病的风险。从历史上看，研究人员一直专注于三种生物标志物：在大脑 成团块的淀粉样蛋白；形成神经原纤维缠结的 tau 蛋白；和脑萎缩，这在 CT 或 MRI 扫描中可见。2018 年，一组神经科学专家创建了一个称为 AT(N) 框架的框架——A 代表淀粉样蛋白，T 代表 tau，(N) 代表神经变性或萎缩，希望推进临床试验。AT(N) 框架的工作对于第一种降低淀粉样 蛋白的药物 (aducanumab) 的开发至关重要，该药物现已获得 FDA 批准。</p><img src=\"./img/img5.jpg\" alt=\"\"> <p>HABS-HD 旨在通过解决初始框架中的一个关键复杂问题：缺乏多样性，将 AT(N) 框架提升到一个新的水平。几乎所有支持框架本身的数据 临床试验都来自非西班牙裔白人的研究。美国人口普查局预测，到 2060 年，美国将主要变成“非白人”，其中 15% 的人口是非裔美国人，27. 5% 是西班牙裔。因此，对于 43% 的美国人口，迫切需要了解 AT(N) 框架和相关的基于生物标 志物的疗法的相关性。 “研究表明，与非西班牙裔白人相比，西班牙裔和非裔美国人患轻度认知障碍和阿尔茨海默病的风险要高得多，”Stevens INI 主任Arthur ga 博士说，他是该项目的神经影像学和信息学负责人HABS-HD 研究。“HABS-HD 是同类研究中的首例——一项使用 AT(N) 框架的大规模研 究，其队列更能代表我们所生活的种族多样性。” HABS-HD 研究现已招募了近 1,000 名墨西哥裔美国人和 1,000 名非西班牙裔白人，另外 1,000名非裔美国人的招募正在进行中。所有参与 接受了包括面试、功能检查、抽血、记忆和认知测试、脑部 MRI 和临床实验室血液检查在内的程序。德克萨斯州沃思堡转化研究所每隔 24 到 3 0 个月会见一次参与者。研究团队在社会、环境和行为因素的背景下研究疾病的生物学。鉴于 AD 和其他脑部疾病对社区的影响似乎不同，为了反 映不同的人群，需要进行研究以了解每个人中的这种破坏性疾病。 作为 HABS-HD 神经影像学和信息学的领导者，Toga 与共同负责人兼史蒂文斯 INI 成员Meredith Braskie 博士一起，通过史蒂文斯 INI 内 神经影像实验室 ( LONI )监督神经影像采集、存储和维护。LONI 使用尖端成像和信息学来收集和分析大脑图像。Toga 还负责阿尔茨海默病神经 影像学计划的信息学工作，这是阿尔茨海默病研究中规模最大、运行时间最长的生物标志物发现工作，以及全球阿尔茨海默病协会互动网络，它 汇集了世界上最大的阿尔茨海默病数据集。Toga和他的团队已准备好通过管理数据并根据 NIH 数据共享政策向合格研究人员提供数据集，从而 在该项目中取得长足进步，从而造福于更广泛的科学界。 “我们在解决健康差异的大数据和研究方面的丰富经验将使我们能够迅速应对与该项目雄心勃勃的目标相关的挑战，”Toga 说，他也是眼科 经学、精神病学和行为科学、放射学的教务长教授，以及工程和凯克学院神经科学的 Ghada Irani 教席。“HABS-HD 研究象征着我们在史蒂文 斯 INI 的目标是高度协作，并利用我们的专业知识来改变阿尔茨海默氏症和相关痴呆症的研究，不排除受这些疾病影响如此深远的种族群体。” </p>"
     },
     {
        "title":"人工智能-深度学习应用研究",
        "ds":"导师：Bjorn Schuller 帝国理工学院终身教授",
        "jj":"项目内容：教授神经网络和机器深度学习中模式识别的基本原理，作为应用领域的典范。",
        "img":"./img/img2.jpg",  
        "time":"2022-03-06", 
        "body":"<p> 提供的一项为期五年、价值 1.49 亿美元的拨款合作伙伴关系的五家机构之一，旨在解决阿尔茨海默病的健康差异问题研究。这笔赠款将继续 健康和老龄化大脑研究——健康差异 (HABS-HD)，这是迄今为止在不同社区进行的最全面的阿尔茨海默病 (AD) 研究。该项目的主要研究人员 包括北德克萨斯大学健康科学中心的 Sid O-Bryant 博士和 Leigh Johnson 博士；加州大学旧金山分校威尔神经科学研究所的医学博士 Kristine Yaffe；Robert Rissman，加州大学圣地亚哥分校博士；和南加州大学的 Arthur W. Toga 博士。 AD 研究中最重大的挑战之一是确定生物标志物，以确定谁有患这种疾病的风险。从历史上看，研究人员一直专注于三种生物标志物：在大脑 成团块的淀粉样蛋白；形成神经原纤维缠结的 tau 蛋白；和脑萎缩，这在 CT 或 MRI 扫描中可见。2018 年，一组神经科学专家创建了一个称为 AT(N) 框架的框架——A 代表淀粉样蛋白，T 代表 tau，(N) 代表神经变性或萎缩，希望推进临床试验。AT(N) 框架的工作对于第一种降低淀粉样 蛋白的药物 (aducanumab) 的开发至关重要，该药物现已获得 FDA 批准。</p><img src=\"./img/img5.jpg\" alt=\"\"> <p>HABS-HD 旨在通过解决初始框架中的一个关键复杂问题：缺乏多样性，将 AT(N) 框架提升到一个新的水平。几乎所有支持框架本身的数据 临床试验都来自非西班牙裔白人的研究。美国人口普查局预测，到 2060 年，美国将主要变成“非白人”，其中 15% 的人口是非裔美国人，27. 5% 是西班牙裔。因此，对于 43% 的美国人口，迫切需要了解 AT(N) 框架和相关的基于生物标 志物的疗法的相关性。 “研究表明，与非西班牙裔白人相比，西班牙裔和非裔美国人患轻度认知障碍和阿尔茨海默病的风险要高得多，”Stevens INI 主任Arthur ga 博士说，他是该项目的神经影像学和信息学负责人HABS-HD 研究。“HABS-HD 是同类研究中的首例——一项使用 AT(N) 框架的大规模研 究，其队列更能代表我们所生活的种族多样性。” HABS-HD 研究现已招募了近 1,000 名墨西哥裔美国人和 1,000 名非西班牙裔白人，另外 1,000名非裔美国人的招募正在进行中。所有参与 接受了包括面试、功能检查、抽血、记忆和认知测试、脑部 MRI 和临床实验室血液检查在内的程序。德克萨斯州沃思堡转化研究所每隔 24 到 3 0 个月会见一次参与者。研究团队在社会、环境和行为因素的背景下研究疾病的生物学。鉴于 AD 和其他脑部疾病对社区的影响似乎不同，为了反 映不同的人群，需要进行研究以了解每个人中的这种破坏性疾病。 作为 HABS-HD 神经影像学和信息学的领导者，Toga 与共同负责人兼史蒂文斯 INI 成员Meredith Braskie 博士一起，通过史蒂文斯 INI 内 神经影像实验室 ( LONI )监督神经影像采集、存储和维护。LONI 使用尖端成像和信息学来收集和分析大脑图像。Toga 还负责阿尔茨海默病神经 影像学计划的信息学工作，这是阿尔茨海默病研究中规模最大、运行时间最长的生物标志物发现工作，以及全球阿尔茨海默病协会互动网络，它 汇集了世界上最大的阿尔茨海默病数据集。Toga和他的团队已准备好通过管理数据并根据 NIH 数据共享政策向合格研究人员提供数据集，从而 在该项目中取得长足进步，从而造福于更广泛的科学界。 “我们在解决健康差异的大数据和研究方面的丰富经验将使我们能够迅速应对与该项目雄心勃勃的目标相关的挑战，”Toga 说，他也是眼科 经学、精神病学和行为科学、放射学的教务长教授，以及工程和凯克学院神经科学的 Ghada Irani 教席。“HABS-HD 研究象征着我们在史蒂文 斯 INI 的目标是高度协作，并利用我们的专业知识来改变阿尔茨海默氏症和相关痴呆症的研究，不排除受这些疾病影响如此深远的种族群体。” </p>"
     },
     {
        "title":"企业战略与供应链管理案例",
        "ds":"导师：Omeed Selbe 南加州大学马歇尔商学院",
        "jj":"项目内容：主要对各行业中龙头企业进行供应链管理和运营分析，剖析企业管理供应链管理规则。",
        "img":"./img/img3.jpg",
        "time":"2022-03-06",
        "body":"<p> 提供的一项为期五年、价值 1.49 亿美元的拨款合作伙伴关系的五家机构之一，旨在解决阿尔茨海默病的健康差异问题研究。这笔赠款将继续 健康和老龄化大脑研究——健康差异 (HABS-HD)，这是迄今为止在不同社区进行的最全面的阿尔茨海默病 (AD) 研究。该项目的主要研究人员 包括北德克萨斯大学健康科学中心的 Sid O-Bryant 博士和 Leigh Johnson 博士；加州大学旧金山分校威尔神经科学研究所的医学博士 Kristine Yaffe；Robert Rissman，加州大学圣地亚哥分校博士；和南加州大学的 Arthur W. Toga 博士。 AD 研究中最重大的挑战之一是确定生物标志物，以确定谁有患这种疾病的风险。从历史上看，研究人员一直专注于三种生物标志物：在大脑 成团块的淀粉样蛋白；形成神经原纤维缠结的 tau 蛋白；和脑萎缩，这在 CT 或 MRI 扫描中可见。2018 年，一组神经科学专家创建了一个称为 AT(N) 框架的框架——A 代表淀粉样蛋白，T 代表 tau，(N) 代表神经变性或萎缩，希望推进临床试验。AT(N) 框架的工作对于第一种降低淀粉样 蛋白的药物 (aducanumab) 的开发至关重要，该药物现已获得 FDA 批准。</p><img src=\"./img/img5.jpg\" alt=\"\"> <p>HABS-HD 旨在通过解决初始框架中的一个关键复杂问题：缺乏多样性，将 AT(N) 框架提升到一个新的水平。几乎所有支持框架本身的数据 临床试验都来自非西班牙裔白人的研究。美国人口普查局预测，到 2060 年，美国将主要变成“非白人”，其中 15% 的人口是非裔美国人，27. 5% 是西班牙裔。因此，对于 43% 的美国人口，迫切需要了解 AT(N) 框架和相关的基于生物标 志物的疗法的相关性。 “研究表明，与非西班牙裔白人相比，西班牙裔和非裔美国人患轻度认知障碍和阿尔茨海默病的风险要高得多，”Stevens INI 主任Arthur ga 博士说，他是该项目的神经影像学和信息学负责人HABS-HD 研究。“HABS-HD 是同类研究中的首例——一项使用 AT(N) 框架的大规模研 究，其队列更能代表我们所生活的种族多样性。” HABS-HD 研究现已招募了近 1,000 名墨西哥裔美国人和 1,000 名非西班牙裔白人，另外 1,000名非裔美国人的招募正在进行中。所有参与 接受了包括面试、功能检查、抽血、记忆和认知测试、脑部 MRI 和临床实验室血液检查在内的程序。德克萨斯州沃思堡转化研究所每隔 24 到 3 0 个月会见一次参与者。研究团队在社会、环境和行为因素的背景下研究疾病的生物学。鉴于 AD 和其他脑部疾病对社区的影响似乎不同，为了反 映不同的人群，需要进行研究以了解每个人中的这种破坏性疾病。 作为 HABS-HD 神经影像学和信息学的领导者，Toga 与共同负责人兼史蒂文斯 INI 成员Meredith Braskie 博士一起，通过史蒂文斯 INI 内 神经影像实验室 ( LONI )监督神经影像采集、存储和维护。LONI 使用尖端成像和信息学来收集和分析大脑图像。Toga 还负责阿尔茨海默病神经 影像学计划的信息学工作，这是阿尔茨海默病研究中规模最大、运行时间最长的生物标志物发现工作，以及全球阿尔茨海默病协会互动网络，它 汇集了世界上最大的阿尔茨海默病数据集。Toga和他的团队已准备好通过管理数据并根据 NIH 数据共享政策向合格研究人员提供数据集，从而 在该项目中取得长足进步，从而造福于更广泛的科学界。 “我们在解决健康差异的大数据和研究方面的丰富经验将使我们能够迅速应对与该项目雄心勃勃的目标相关的挑战，”Toga 说，他也是眼科 经学、精神病学和行为科学、放射学的教务长教授，以及工程和凯克学院神经科学的 Ghada Irani 教席。“HABS-HD 研究象征着我们在史蒂文 斯 INI 的目标是高度协作，并利用我们的专业知识来改变阿尔茨海默氏症和相关痴呆症的研究，不排除受这些疾病影响如此深远的种族群体。” </p>"
     }
]